name: Extraction
version: 1.0.0

config:
  data:
    - name: mimic-iv
      version: "3.1"
      path: /workspaces/example/data/physionet.org/files/mimiciv/3.1
    - name: eicu-crd
      version: "2.0"
      path: /workspaces/example/data/physionet.org/files/eicu-crd/2.0
    - name: nwicu
      version: "0.1.0"
      path: /workspaces/example/data/physionet.org/files/nwicu-northwestern-icu/0.1.0
