site_name: WeavEHR
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started:
      - Package Overview: "getting_started/overview.md"
      - Installation: "getting_started/installation.md"
      - Basic Usage: "getting_started/basic_usage.md"
      - Contributing: "getting_started/contributing.md"
  - User Guide:
      - Projects and the Pipeline: "user_guide/pipeline.md"
      - Extraction Configuration: "user_guide/extraction.md"
      - Dataset Versions and Variants: "user_guide/versioning.md"
      - Concept Configuration: "user_guide/concepts.md"
      - Expression Language: "user_guide/expressions.md"
  - Architecture:
      - Introduction and Goals: "arc/introduction.md"
      - Architecture Constraints: "arc/constraints.md"
      - Context and Scope: "arc/context.md"
      - Solution Strategy: "arc/strategy.md"
      - Building Block View: "arc/building_block.md"
      - Runtime View: "arc/runtime.md"
      - Deployment view: "arc/deployment.md"
      - Crosscutting Concepts: "arc/concepts.md"
      - Architecture Decisions: "arc/decisions.md"
      - Quality Requirements: "arc/quality.md"
      - Risks and Technical Debt: "arc/risks.md"
      - Glossary: "arc/glossary.md"
  - API Reference: reference/

copyright: Copyright &copy; 2023 AIDH MS
repo_url: "https://github.com/aidh-ms/WeavEHR"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aidh-ms/WeavEHR

extra_css:
  - assets/css/code_select.css
  - assets/css/fonts.css

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.extra
  - footnotes
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
  - macros:
      include_dir: ./
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: google
