path: ed/triage.csv.gz

columns:
  # subject_id and extentions
  - name: subject_id
    type: int64
  - name: stay_id
    type: int64
  # db fields - times
  # db fields - values
  - name: temperature
    type: float32
  - name: heartrate
    type: float32
  - name: resprate
    type: float32
  - name: o2sat
    type: float32
  - name: sbp
    type: float32
  - name: dbp
    type: float32
  - name: pain
    type: string
  - name: acuity
    type: int64
  - name: chiefcomplaint
    type: string
join:
  - name: edstays
    path: ed/edstays.csv.gz
    columns:
      - name: stay_id
        type: int64
      - name: hadm_id
        type: int64
      - name: intime
        type: datetime
        params:
          format: "%Y-%m-%d %H:%M:%S"
    both_on:
      - stay_id

event_defaults:
  subject_id: col(subject_id)
  time: col(intime)
  extension:
    stay_id: col(stay_id)
    hadm_id: col(hadm_id)

events:
  - name: ED_TRIAGE
    columns:
      code:
        - const("ED_TRIAGE")
      numeric_value: col(acuity)
      text_value: col("chiefcomplaint")

  - name: ED_TRIAGE_TEMPERATURE
    columns:
      code:
        - const("ED_TRIAGE_TEMPERATURE")
      numeric_value: col(temperature)

  - name: ED_TRIAGE_HEARTRATE
    columns:
      code:
        - const("ED_TRIAGE_HEARTRATE")
      numeric_value: col(heartrate)

  - name: ED_TRIAGE_RESPRATE
    columns:
      code:
        - const("ED_TRIAGE_RESPRATE")
      numeric_value: col(resprate)

  - name: ED_TRIAGE_O2SAT
    columns:
      code:
        - const("ED_TRIAGE_O2SAT")
      numeric_value: col(o2sat)

  - name: ED_TRIAGE_SBP
    columns:
      code:
        - const("ED_TRIAGE_SBP")
      numeric_value: col(sbp)

  - name: ED_TRIAGE_DBP
    columns:
      code:
        - const("ED_TRIAGE_DBP")
      numeric_value: col(dbp)

  - name: ED_TRIAGE_PAIN
    columns:
      code:
        - const("ED_TRIAGE_PAIN")
      text_value: col(pain)
