path: ed/edstays.csv.gz

columns:
  # subject_id and extentions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  # db fields - times
  - name: intime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: outtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: gender
    type: string
  - name: race
    type: string
  - name: arrival_transport
    type: string
  - name: disposition
    type: string

event_defaults:
  subject_id: col(subject_id)
  time: col(intime)
  extension:
    stay_id: col(stay_id)
    hadm_id: col(hadm_id)

events:
  - name: ED_INTIME
    columns:
      code:
        - const("ED_INTIME")
      text_value: col(arrival_transport)

  - name: ED_OUTTIME
    columns:
      time: col(outtime)
      code:
        - const("ED_OUTTIME")
      text_value: col(disposition)

  - name: GENDER
    columns:
      code:
        - col("gender")

  - name: RACE
    columns:
      code:
        - col("race")
