# SICdb v1.0.6 -- laboratory id(s) 611 [ricu ck]
type: simple
mappings:
  - pattern:
      table: laboratory
      event: LAB
      code: "^(611)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
