type: simple
mappings:
  - pattern:
      table: chartevents
      event: CHART
      code: (220227(//.*)?)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
    filters:
      - drop_na(numeric_value)
      - drop_if(col(numeric_value) < 0 or col(numeric_value) > 100)

  - pattern:
      table: labevents
      event: LAB
      code: (50817(//.*)?)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
    filters:
      - drop_na(numeric_value)
      - drop_if(col(numeric_value) < 0 or col(numeric_value) > 100)
