type: simple
mappings:
  - pattern:
      table: inputevents
      event: INFUSION_END
      code: (223258(//.*)?)
    columns:
      numeric_value: col(rate)
      text_value: col(text_value)
    filters:
      - rateuom == "units/hour"
      - drop_na(numeric_value)
