type: complex
concept_transformer: open_icu.steps.concept.transformer.sofa.SofaRespiratoryTransformer
concepts:
  - O2_partial_pressure.1.0.0
  - fraction_of_inspired_oxygen.1.0.0
  - mechanical_ventilation_windows.1.0.0
