type: complex
concept_transformer: open_icu.steps.concept.transformer.sofa.SofaTransformer
concepts:
  - sofa_respiratory.1.0.0
  - sofa_coagulation.1.0.0
  - sofa_liver.1.0.0
  - sofa_cardiovascular.1.0.0
  - sofa_cns.1.0.0
  - sofa_renal.1.0.0
