# HiRID v1.1.1 -- observations variableid(s) 24000330 [ricu ast]
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "^(24000330)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
