# HiRID v1.1.1 -- observations variableid(s) 24000536 [ricu fgn]; converts to the concept unit (* 100)
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "^(24000536)(//.*)?$"
    columns:
      numeric_value: col(numeric_value) * 100
      text_value: col(text_value)
