# HiRID v1.1.1 -- observations variableid(s) 10000300 [ricu egcs]
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "^(10000300)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
