# HiRID v1.1.1 -- observations variableid(s) 20004410 [ricu ptt]
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "^(20004410)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
