# HiRID v1.1.1 -- observations variableid(s) 15001565 [ricu rass]
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "^(15001565)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
