# HiRID v1.1.1 -- observations variableid(s) 20000700 [ricu wbc]
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "^(20000700)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
