# AUMCdb (OMOP CDM 5.4 via AMSTEL) -- maps OMOP measurement_concept_id:
#   3020460 = C reactive protein [Mass/volume] in Serum or Plasma
type: simple
mappings:
  - pattern:
      table: measurement
      event: MEASUREMENT
      code: "^3020460(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
