# AUMCdb (OMOP CDM 5.4 via AMSTEL) -- maps OMOP measurement_concept_id:
#   40762531 = MCH [Entitic substance]
type: simple
mappings:
  - pattern:
      table: measurement
      event: MEASUREMENT
      code: "^40762531(//.*)?$"
    columns:
      numeric_value: col(numeric_value) * 0.016113
      text_value: col(text_value)
