type: simple
mappings:
  - pattern:
      table: medication
      event: MEDICATION_ORDER
      code: (?i)((d50|dextrose.+50 ?%))
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: infusiondrug
      event: INFUSION
      code: (?i)((d10|dextrose.+10 ?%).+ml/hr)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
