type: simple
mappings:
- pattern:
    table: vitalperiodic
    event: O2_SATURATION_PULSE_OXIMETRY
    code: ^VITALS_PERIODIC//%$
  columns:
    numeric_value: col(numeric_value)
    text_value: col(text_value)
- pattern:
    table: lab
    event: LAB
    code: ^(O2\ Sat\ \(%\))(//.*)?$
  columns:
    numeric_value: col(numeric_value)
    text_value: col(text_value)
